# Generated by Django 5.0.1 on 2026-04-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('open', 'Open'), ('ranking', 'Ranking'), ('invitational', 'Invitational'), ('club', 'Club Level')], default='open', max_length=20)),
                ('category', models.CharField(choices=[('open', 'Open'), ('u21', 'Under 21'), ('veterans', 'Veterans 40+'), ('ladies', 'Ladies')], default='open', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_map_link', models.URLField(blank=True, help_text='Google Maps link to venue')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prize_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='tournaments/posters/')),
                ('contact_phone', models.CharField(help_text='WhatsApp number (without +977)', max_length=20)),
                ('max_players', models.PositiveIntegerField(default=32)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('club_or_hall', models.CharField(blank=True, help_text='Optional', max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Upload eSewa / Khalti screenshot if entry fee applies', null=True, upload_to='tournaments/payments/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['registered_at'],
                'unique_together': {('tournament', 'phone')},
            },
        ),
    ]
