# Generated by Django 5.0.1 on 2026-05-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Tick if exact dates are not yet confirmed'),
        ),
    ]
